package com.tahbeer.app.details.utils

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import com.tahbeer.app.details.presentation.components.SubtitleStyles
import com.tahbeer.app.details.presentation.components.VerticalPosition

fun Color.toAssColorString(): String {
    val a = ((1 - this.alpha) * 255).toInt().toString(16).padStart(2, '0').uppercase()
    val r = (this.red * 255).toInt().toString(16).padStart(2, '0').uppercase()
    val g = (this.green * 255).toInt().toString(16).padStart(2, '0').uppercase()
    val b = (this.blue * 255).toInt().toString(16).padStart(2, '0').uppercase()
    return "&H$a$b$g$r"
}


fun VerticalPosition.toAssAlignmentCode(): Int {
    return when (this) {
        VerticalPosition.TOP -> 8
        VerticalPosition.CENTER -> 5
        VerticalPosition.BOTTOM -> 2
    }
}

fun generateAssHeader(styles: SubtitleStyles, videoWidth: Int, videoHeight: Int): String {

    // Mappings
    val isBold = if (styles.fontWeight >= FontWeight.Bold) -1 else 0
    val alignmentCode = styles.verticalPosition.toAssAlignmentCode()
    val primaryColor = styles.textColor.toAssColorString()
    val outlineColor = styles.outlineColor.toAssColorString()

    // ASS Header Block
    val header = """
[Script Info]
; Script generated by Tahbeer
Title: Generated Subtitles
ScriptType: v4.00+
WrapStyle: 0
PlayResX: $videoWidth
PlayResY: $videoHeight
ScaledBorderAndShadow: yes
        
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: CustomStyle,IBM Plex Sans Arabic,${styles.fontSize},$primaryColor,&H0000FFFF,$outlineColor,&H00000000,$isBold,0,0,0,100,100,0,0,1,${styles.outlineWidth},0,$alignmentCode,10,10,20,0
    """.trimIndent()

    return header
}