package com.tahbeer.app.home.domain.model

data class VoskModel(
    val lang: String,
    val size: Long,
    val url: String,
    val isDownloaded: Boolean = false,
    val downloadingProgress: Float? = null
)

object VoskModelList {
    val models = listOf(
        VoskModel(
            "ar",
            104351896,
            "https://alphacephei.com/vosk/models/vosk-model-small-ar-0.3.zip"
        ),
        VoskModel(
            "ar-tn",
            165703754,
            "https://alphacephei.com/vosk/models/vosk-model-small-ar-tn-0.1-linto.zip"
        ),
        VoskModel(
            "ca",
            43405881,
            "https://alphacephei.com/vosk/models/vosk-model-small-ca-0.4.zip"
        ),
        VoskModel(
            "zh",
            43898754,
            "https://alphacephei.com/vosk/models/vosk-model-small-cn-0.22.zip"
        ),
        VoskModel(
            "cs",
            46088666,
            "https://alphacephei.com/vosk/models/vosk-model-small-cs-0.4-rhasspy.zip"
        ),
        VoskModel(
            "de",
            46499967,
            "https://alphacephei.com/vosk/models/vosk-model-small-de-0.15.zip"
        ),
        VoskModel(
            "en-gb",
            42757500,
            "https://alphacephei.com/vosk/models/vosk-model-small-en-gb-0.15.zip"
        ),
        VoskModel(
            "en-in",
            37573330,
            "https://alphacephei.com/vosk/models/vosk-model-small-en-in-0.4.zip"
        ),
        VoskModel(
            "en-us",
            41205931,
            "https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip"
        ),
        VoskModel(
            "eo",
            43839401,
            "https://alphacephei.com/vosk/models/vosk-model-small-eo-0.42.zip"
        ),
        VoskModel(
            "es",
            39817833,
            "https://alphacephei.com/vosk/models/vosk-model-small-es-0.42.zip"
        ),
        VoskModel(
            "fa",
            53431220,
            "https://alphacephei.com/vosk/models/vosk-model-small-fa-0.42.zip"
        ),
        VoskModel(
            "fr",
            42233323,
            "https://alphacephei.com/vosk/models/vosk-model-small-fr-0.22.zip"
        ),
        VoskModel(
            "gu",
            108054987,
            "https://alphacephei.com/vosk/models/vosk-model-small-gu-0.42.zip"
        ),
        VoskModel(
            "hi",
            44458845,
            "https://alphacephei.com/vosk/models/vosk-model-small-hi-0.22.zip"
        ),
        VoskModel(
            "it",
            49665141,
            "https://alphacephei.com/vosk/models/vosk-model-small-it-0.22.zip"
        ),
        VoskModel(
            "ja",
            49704573,
            "https://alphacephei.com/vosk/models/vosk-model-small-ja-0.22.zip"
        ),
        VoskModel(
            "ko",
            86914329,
            "https://alphacephei.com/vosk/models/vosk-model-small-ko-0.22.zip"
        ),
        VoskModel(
            "kk",
            43739114,
            "https://alphacephei.com/vosk/models/vosk-model-small-kz-0.15.zip"
        ),
        VoskModel(
            "nl",
            40441176,
            "https://alphacephei.com/vosk/models/vosk-model-small-nl-0.22.zip"
        ),
        VoskModel(
            "pl",
            52979372,
            "https://alphacephei.com/vosk/models/vosk-model-small-pl-0.22.zip"
        ),
        VoskModel(
            "pt",
            32453112,
            "https://alphacephei.com/vosk/models/vosk-model-small-pt-0.3.zip"
        ),
        VoskModel(
            "ru",
            46236750,
            "https://alphacephei.com/vosk/models/vosk-model-small-ru-0.22.zip"
        ),
        VoskModel(
            "sv",
            303504931,
            "https://alphacephei.com/vosk/models/vosk-model-small-sv-rhasspy-0.15.zip"
        ),
        VoskModel(
            "te",
            60544249,
            "https://alphacephei.com/vosk/models/vosk-model-small-te-0.42.zip"
        ),
        VoskModel(
            "tg",
            51879043,
            "https://alphacephei.com/vosk/models/vosk-model-small-tg-0.22.zip"
        ),
        VoskModel(
            "tr",
            36855784,
            "https://alphacephei.com/vosk/models/vosk-model-small-tr-0.3.zip"
        ),
        VoskModel(
            "uk",
            143914407,
            "https://alphacephei.com/vosk/models/vosk-model-small-uk-v3-small.zip"
        ),
        VoskModel(
            "uz",
            51061189,
            "https://alphacephei.com/vosk/models/vosk-model-small-uz-0.22.zip"
        ),
        VoskModel("vi", 33656337, "https://alphacephei.com/vosk/models/vosk-model-small-vn-0.4.zip")
    )

    fun getModelsByLanguage(language: String): List<VoskModel> {
        return models.filter { it.lang == language }
    }
}
